name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: "recursive"

      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: 'stable'
          check-latest: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v $(go list ./... | grep -v "/api\|/core") -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@main
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Refresh Go Report Card
        uses: creekorful/goreportcard-action@master
