name: update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: "recursive"

      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: 'stable'
          check-latest: true

      - name: Run update.sh
        run: |
          chmod +x ./update.sh ./generate.sh
          ./update.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
